"""Employee/Department use cases barrel."""
from app.application.employees.department_crud import (
    CreateDepartmentInput,
    CreateDepartmentUseCase,
    DeleteDepartmentUseCase,
    GetDepartmentUseCase,
    ListDepartmentsUseCase,
    UpdateDepartmentInput,
    UpdateDepartmentUseCase,
)
from app.application.employees.employee_crud import (
    CreateEmployeeInput,
    CreateEmployeeUseCase,
    DeleteEmployeeUseCase,
    GetEmployeeUseCase,
    LinkUserInput,
    LinkUserUseCase,
    ListEmployeesInput,
    ListEmployeesResult,
    ListEmployeesUseCase,
    UnlinkUserUseCase,
    UpdateEmployeeInput,
    UpdateEmployeeUseCase,
)

__all__ = [
    "CreateDepartmentInput",
    "CreateDepartmentUseCase",
    "UpdateDepartmentInput",
    "UpdateDepartmentUseCase",
    "DeleteDepartmentUseCase",
    "ListDepartmentsUseCase",
    "GetDepartmentUseCase",
    "CreateEmployeeInput",
    "CreateEmployeeUseCase",
    "UpdateEmployeeInput",
    "UpdateEmployeeUseCase",
    "DeleteEmployeeUseCase",
    "ListEmployeesInput",
    "ListEmployeesResult",
    "ListEmployeesUseCase",
    "GetEmployeeUseCase",
    "LinkUserInput",
    "LinkUserUseCase",
    "UnlinkUserUseCase",
]